// <auto-generated />
using System;
using AutodecisionCore.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutodecisionCore.Data.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230424200303_AlterTableAutoApprovalRuleDescriptionNullable")]
    partial class AlterTableAutoApprovalRuleDescriptionNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AutodecisionCore.Data.Models.Allotment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("account_number");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("loan_number");

                    b.Property<string>("ReconciliationSystem")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("reconciliation_system");

                    b.Property<string>("RoutingNumber")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("routing_number");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_allotments");

                    b.ToTable("allotments", (string)null);
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutoApprovalFundingMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("FundingMethod")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("funding_method");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_allowed");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id")
                        .HasName("pk_auto_approval_funding_methods");

                    b.ToTable("auto_approval_funding_methods", (string)null);
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutoApprovalPaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_allowed");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("varchar(64)")
                        .HasColumnName("payment_type");

                    b.HasKey("Id")
                        .HasName("pk_auto_approval_payment_types");

                    b.ToTable("auto_approval_payment_types", (string)null);
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutoApprovalUwCluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAllowed")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_allowed");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("UwCluster")
                        .IsRequired()
                        .HasColumnType("varchar(16)")
                        .HasColumnName("uw_cluster");

                    b.HasKey("Id")
                        .HasName("pk_auto_approval_uwcluster");

                    b.ToTable("auto_approval_uwcluster", (string)null);
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationCore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("LoanNumber")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("loan_number");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProcessingVersion")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("processing_version");

                    b.Property<int>("Status")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_application_cores");

                    b.HasIndex("LoanNumber")
                        .HasDatabaseName("IX_ApplicationsCore_LoanNumber");

                    b.ToTable("application_cores", (string)null);
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("ApplicationCoreId")
                        .HasColumnType("int")
                        .HasColumnName("application_core_id");

                    b.Property<string>("ApprovalNote")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("approval_note");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("approved_at");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int")
                        .HasColumnName("approved_by");

                    b.Property<string>("ApprovedByName")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("approved_by_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("description");

                    b.Property<string>("FlagCode")
                        .IsRequired()
                        .HasColumnType("varchar(4)")
                        .HasColumnName("flag_code");

                    b.Property<bool>("InternalFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("internal_flag");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("requested_at");

                    b.Property<int>("Status")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_application_flags");

                    b.HasIndex("ApplicationCoreId")
                        .HasDatabaseName("ix_application_flags_application_core_id");

                    b.ToTable("application_flags", (string)null);
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationFlagsInternalMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("ApplicationFlagId")
                        .HasColumnType("int")
                        .HasColumnName("application_flag_id");

                    b.Property<int>("Code")
                        .HasMaxLength(5)
                        .HasColumnType("int")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("message");

                    b.Property<int>("MessageTypeId")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasColumnName("message_type_id");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.HasKey("Id")
                        .HasName("pk_application_flags_internal_messages");

                    b.HasIndex("ApplicationFlagId")
                        .HasDatabaseName("ix_application_flags_internal_messages_application_flag_id");

                    b.ToTable("application_flags_internal_messages", (string)null);
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("ApplicationCoreId")
                        .HasColumnType("int")
                        .HasColumnName("application_core_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("processed_at");

                    b.Property<int>("ProcessingVersion")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("processing_version");

                    b.Property<int>("Status")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_application_processes");

                    b.HasIndex("ApplicationCoreId")
                        .HasDatabaseName("ix_application_processes_application_core_id");

                    b.ToTable("application_processes", (string)null);
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.AutoApprovalRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int?>("ApplicationCoreId")
                        .HasColumnType("int")
                        .HasColumnName("application_core_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("rule_name");

                    b.Property<int>("Status")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_auto_approval_rules");

                    b.HasIndex("ApplicationCoreId")
                        .HasDatabaseName("ix_auto_approval_rules_application_core_id");

                    b.ToTable("auto_approval_rules", (string)null);
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.Flag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("description");

                    b.Property<bool>("InternalFlag")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("internal_flag");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_flags");

                    b.ToTable("flags", (string)null);
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.HealthCheck", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_health_checks");

                    b.ToTable("health_checks", (string)null);
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationFlag", b =>
                {
                    b.HasOne("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationCore", null)
                        .WithMany("ApplicationFlags")
                        .HasForeignKey("ApplicationCoreId")
                        .HasConstraintName("fk_application_flags_application_cores_application_core_id");
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationFlagsInternalMessage", b =>
                {
                    b.HasOne("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationFlag", null)
                        .WithMany("ApplicationFlagsInternalMessage")
                        .HasForeignKey("ApplicationFlagId")
                        .HasConstraintName("fk_application_flags_internal_messages_application_flags_applic");
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationProcess", b =>
                {
                    b.HasOne("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationCore", null)
                        .WithMany("ApplicationProcesses")
                        .HasForeignKey("ApplicationCoreId")
                        .HasConstraintName("fk_application_processes_application_cores_application_core_id");
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.AutoApprovalRule", b =>
                {
                    b.HasOne("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationCore", null)
                        .WithMany("AutoApprovalRules")
                        .HasForeignKey("ApplicationCoreId")
                        .HasConstraintName("fk_auto_approval_rules_application_cores_application_core_id");
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationCore", b =>
                {
                    b.Navigation("ApplicationFlags");

                    b.Navigation("ApplicationProcesses");

                    b.Navigation("AutoApprovalRules");
                });

            modelBuilder.Entity("AutodecisionCore.Data.Models.AutodecisionCoreAggregate.ApplicationFlag", b =>
                {
                    b.Navigation("ApplicationFlagsInternalMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
